name: open_director
description: Open Director. Video editor.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.2+5

# dart version
# https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md
# 2.5.0 - 2019-09-10
# 2.4.1 - 2019-08-07
# 2.4.0 - 2019-06-27
environment:
  sdk: ">=2.1.0 <2.5.1"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: 1.1.6+3
  path: 1.6.4
  rxdart: 0.22.2
  get_it: 1.0.3+2
  file_picker: 1.3.8
  path_provider: 1.2.0
  flutter_ffmpeg: 0.2.7
  video_player:
    path: ./local_plugins/video_player
  permission_handler: 3.2.2
  intl: 0.15.8
  open_file: 2.0.3
  firebase_analytics: 5.0.2
  firebase_crashlytics: 0.1.0+3
  logger: 0.7.0+2
  logger_flutter: 0.7.1
  flutter_colorpicker: 0.2.6
  dotted_border: 1.0.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 0.7.3 # flutter pub run flutter_launcher_icons:main
  flutter_native_splash: 0.1.7+2 # flutter pub pub run flutter_native_splash:create

flutter_icons:
  image_path_android: "assets/icon-710x599.png"
  image_path_ios: "assets/icon-710x599.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "assets/background.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/icon-foreground-432x432.png" # only available for Android 8.0 devices and above

flutter_native_splash:
  image: assets/splash.png
  color: "222222"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  - family: Amaranth
    fonts:
    - asset: fonts/Amaranth/Amaranth-Bold.ttf
      weight: 700
    - asset: fonts/Amaranth/Amaranth-BoldItalic.ttf
      weight: 700
      style: italic
    - asset: fonts/Amaranth/Amaranth-Italic.ttf
      weight: 400
      style: italic
    - asset: fonts/Amaranth/Amaranth-Regular.ttf
      weight: 400
  - family: Bangers
    fonts:
    - asset: fonts/Bangers/Bangers-Regular.ttf
      weight: 400
  - family: CarterOne
    fonts:
    - asset: fonts/Carter_One/CarterOne-Regular.ttf
      weight: 400
  - family: Chilanka
    fonts:
    - asset: fonts/Chilanka/Chilanka-Regular.ttf
      weight: 400
  - family: Courgette
    fonts:
    - asset: fonts/Courgette/Courgette-Regular.ttf
      weight: 400
  - family: DancingScript
    fonts:
    - asset: fonts/Dancing_Script/DancingScript-Bold.ttf
      weight: 700
    - asset: fonts/Dancing_Script/DancingScript-Regular.ttf
      weight: 400
  - family: GochiHand
    fonts:
    - asset: fonts/Gochi_Hand/GochiHand-Regular.ttf
      weight: 400
  - family: Grenze
    fonts:
    - asset: fonts/Grenze/Grenze-Black.ttf
      weight: 900
    - asset: fonts/Grenze/Grenze-BlackItalic.ttf
      weight: 900
      style: italic
    - asset: fonts/Grenze/Grenze-Bold.ttf
      weight: 700
    - asset: fonts/Grenze/Grenze-BoldItalic.ttf
      weight: 700
      style: italic
    - asset: fonts/Grenze/Grenze-ExtraBold.ttf
      weight: 800
    - asset: fonts/Grenze/Grenze-ExtraBoldItalic.ttf
      weight: 800
      style: italic
    - asset: fonts/Grenze/Grenze-ExtraLight.ttf
      weight: 200
    - asset: fonts/Grenze/Grenze-ExtraLightItalic.ttf
      weight: 200
      style: italic
    - asset: fonts/Grenze/Grenze-Italic.ttf
      weight: 400
      style: italic
    - asset: fonts/Grenze/Grenze-Light.ttf
      weight: 300
    - asset: fonts/Grenze/Grenze-LightItalic.ttf
      weight: 300
      style: italic
    - asset: fonts/Grenze/Grenze-Medium.ttf
      weight: 500
    - asset: fonts/Grenze/Grenze-MediumItalic.ttf
      weight: 500
      style: italic
    - asset: fonts/Grenze/Grenze-Regular.ttf
      weight: 400
    - asset: fonts/Grenze/Grenze-SemiBold.ttf
      weight: 600
    - asset: fonts/Grenze/Grenze-SemiBoldItalic.ttf
      weight: 600
      style: italic
    - asset: fonts/Grenze/Grenze-Thin.ttf
      weight: 100
    - asset: fonts/Grenze/Grenze-ThinItalic.ttf
      weight: 100
      style: italic
  - family: Handlee
    fonts:
    - asset: fonts/Handlee/Handlee-Regular.ttf
      weight: 400
  - family: IndieFlower
    fonts:
    - asset: fonts/Indie_Flower/IndieFlower-Regular.ttf
      weight: 400
  - family: Lato
    fonts:
    - asset: fonts/Lato/Lato-Black.ttf
      weight: 900
    - asset: fonts/Lato/Lato-BlackItalic.ttf
      weight: 900
      style: italic
    - asset: fonts/Lato/Lato-Bold.ttf
      weight: 700
    - asset: fonts/Lato/Lato-BoldItalic.ttf
      weight: 700
      style: italic
    - asset: fonts/Lato/Lato-Light.ttf
      weight: 300
    - asset: fonts/Lato/Lato-LightItalic.ttf
      weight: 300
      style: italic
    - asset: fonts/Lato/Lato-Regular.ttf
      weight: 400
    - asset: fonts/Lato/Lato-RegularItalic.ttf
      weight: 400
      style: italic
    - asset: fonts/Lato/Lato-Thin.ttf
      weight: 100
    - asset: fonts/Lato/Lato-ThinItalic.ttf
      weight: 100
      style: italic
  - family: LibreFranklin
    fonts:
    - asset: fonts/Libre_Franklin/LibreFranklin-Black.ttf
      weight: 900
    - asset: fonts/Libre_Franklin/LibreFranklin-BlackItalic.ttf
      weight: 900
      style: italic
    - asset: fonts/Libre_Franklin/LibreFranklin-Bold.ttf
      weight: 700
    - asset: fonts/Libre_Franklin/LibreFranklin-BoldItalic.ttf
      weight: 700
      style: italic
    - asset: fonts/Libre_Franklin/LibreFranklin-ExtraBold.ttf
      weight: 800
    - asset: fonts/Libre_Franklin/LibreFranklin-ExtraBoldItalic.ttf
      weight: 800
      style: italic
    - asset: fonts/Libre_Franklin/LibreFranklin-ExtraLight.ttf
      weight: 200
    - asset: fonts/Libre_Franklin/LibreFranklin-ExtraLightItalic.ttf
      weight: 200
      style: italic
    - asset: fonts/Libre_Franklin/LibreFranklin-Italic.ttf
      weight: 400
      style: italic
    - asset: fonts/Libre_Franklin/LibreFranklin-Light.ttf
      weight: 300
    - asset: fonts/Libre_Franklin/LibreFranklin-LightItalic.ttf
      weight: 300
      style: italic
    - asset: fonts/Libre_Franklin/LibreFranklin-Medium.ttf
      weight: 500
    - asset: fonts/Libre_Franklin/LibreFranklin-MediumItalic.ttf
      weight: 500
      style: italic
    - asset: fonts/Libre_Franklin/LibreFranklin-Regular.ttf
      weight: 400
    - asset: fonts/Libre_Franklin/LibreFranklin-SemiBold.ttf
      weight: 600
    - asset: fonts/Libre_Franklin/LibreFranklin-SemiBoldItalic.ttf
      weight: 600
      style: italic
    - asset: fonts/Libre_Franklin/LibreFranklin-Thin.ttf
      weight: 100
    - asset: fonts/Libre_Franklin/LibreFranklin-ThinItalic.ttf
      weight: 100
      style: italic
  - family: Lobster
    fonts:
    - asset: fonts/Lobster/Lobster-Regular.ttf
      weight: 400
  - family: LuckiestGuy
    fonts:
    - asset: fonts/Luckiest_Guy/LuckiestGuy-Regular.ttf
      weight: 400
  - family: Mansalva
    fonts:
    - asset: fonts/Mansalva/Mansalva-Regular.ttf
      weight: 400
  - family: Merriweather
    fonts:
    - asset: fonts/Merriweather/Merriweather-Black.ttf
      weight: 900
    - asset: fonts/Merriweather/Merriweather-BlackItalic.ttf
      weight: 900
      style: italic
    - asset: fonts/Merriweather/Merriweather-Bold.ttf
      weight: 700
    - asset: fonts/Merriweather/Merriweather-BoldItalic.ttf
      weight: 700
      style: italic
    - asset: fonts/Merriweather/Merriweather-Italic.ttf
      weight: 400
      style: italic
    - asset: fonts/Merriweather/Merriweather-Light.ttf
      weight: 300
    - asset: fonts/Merriweather/Merriweather-LightItalic.ttf
      weight: 300
      style: italic
    - asset: fonts/Merriweather/Merriweather-Regular.ttf
      weight: 400
  - family: OpenSans
    fonts:
    - asset: fonts/Open_Sans/OpenSans-Bold.ttf
      weight: 700
    - asset: fonts/Open_Sans/OpenSans-BoldItalic.ttf
      weight: 700
      style: italic
    - asset: fonts/Open_Sans/OpenSans-ExtraBold.ttf
      weight: 800
    - asset: fonts/Open_Sans/OpenSans-ExtraBoldItalic.ttf
      weight: 800
      style: italic
    - asset: fonts/Open_Sans/OpenSans-Italic.ttf
      weight: 400
      style: italic
    - asset: fonts/Open_Sans/OpenSans-Light.ttf
      weight: 300
    - asset: fonts/Open_Sans/OpenSans-LightItalic.ttf
      weight: 300
      style: italic
    - asset: fonts/Open_Sans/OpenSans-Regular.ttf
      weight: 400
    - asset: fonts/Open_Sans/OpenSans-SemiBold.ttf
      weight: 600
    - asset: fonts/Open_Sans/OpenSans-SemiBoldItalic.ttf
      weight: 600
      style: italic
  - family: Pacifico
    fonts:
    - asset: fonts/Pacifico/Pacifico-Regular.ttf
      weight: 400
  - family: PermanentMarker
    fonts:
    - asset: fonts/Permanent_Marker/PermanentMarker-Regular.ttf
      weight: 400
  - family: Righteous
    fonts:
    - asset: fonts/Righteous/Righteous-Regular.ttf
      weight: 400
  - family: Roboto
    fonts:
    - asset: fonts/Roboto/Roboto-Black.ttf
      weight: 900
    - asset: fonts/Roboto/Roboto-BlackItalic.ttf
      weight: 900
      style: italic
    - asset: fonts/Roboto/Roboto-Bold.ttf
      weight: 700
    - asset: fonts/Roboto/Roboto-BoldItalic.ttf
      weight: 700
      style: italic
    - asset: fonts/Roboto/Roboto-Italic.ttf
      weight: 400
      style: italic
    - asset: fonts/Roboto/Roboto-Light.ttf
      weight: 300
    - asset: fonts/Roboto/Roboto-LightItalic.ttf
      weight: 300
      style: italic
    - asset: fonts/Roboto/Roboto-Medium.ttf
      weight: 500
    - asset: fonts/Roboto/Roboto-MediumItalic.ttf
      weight: 500
      style: italic
    - asset: fonts/Roboto/Roboto-Regular.ttf
      weight: 400
    - asset: fonts/Roboto/Roboto-RegularItalic.ttf
      weight: 400
      style: italic
    - asset: fonts/Roboto/Roboto-Thin.ttf
      weight: 100
    - asset: fonts/Roboto/Roboto-ThinItalic.ttf
      weight: 100
      style: italic
  - family: SourceSansPro
    fonts:
    - asset: fonts/Source_Sans_Pro/SourceSansPro-Black.ttf
      weight: 900
    - asset: fonts/Source_Sans_Pro/SourceSansPro-BlackItalic.ttf
      weight: 900
      style: italic
    - asset: fonts/Source_Sans_Pro/SourceSansPro-Bold.ttf
      weight: 700
    - asset: fonts/Source_Sans_Pro/SourceSansPro-BoldItalic.ttf
      weight: 700
      style: italic
    - asset: fonts/Source_Sans_Pro/SourceSansPro-ExtraLight.ttf
      weight: 200
    - asset: fonts/Source_Sans_Pro/SourceSansPro-ExtraLightItalic.ttf
      weight: 200
      style: italic
    - asset: fonts/Source_Sans_Pro/SourceSansPro-Italic.ttf
      weight: 400
      style: italic
    - asset: fonts/Source_Sans_Pro/SourceSansPro-Light.ttf
      weight: 300
    - asset: fonts/Source_Sans_Pro/SourceSansPro-LightItalic.ttf
      weight: 300
      style: italic
    - asset: fonts/Source_Sans_Pro/SourceSansPro-Regular.ttf
      weight: 400
    - asset: fonts/Source_Sans_Pro/SourceSansPro-SemiBold.ttf
      weight: 600
    - asset: fonts/Source_Sans_Pro/SourceSansPro-SemiBoldItalic.ttf
      weight: 600
      style: italic

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
